## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.hoststream.localhost`)"

# API and dashboard configuration
api:
  insecure: true
